//! Executable-evidence discovery for test-to-production relationships.
//!
//! Tests are useful behavioral observations: their names and assertions often
//! describe a capability more clearly than the implementation symbol does.
//! This module only identifies observation candidates and assertion calls. The
//! indexer resolves calls and stores the resulting evidence edges behind an
//! explicit experimental flag; it does not alter ranking by itself.

use crate::calls::CallSite;

/// Metadata source marker used to distinguish experimental evidence edges from
/// ordinary, user-created `Tests` edges.
pub const EDGE_SOURCE: &str = "executable_evidence";

/// Return whether a relative path conventionally contains executable tests.
pub fn is_test_path(path: &str) -> bool {
    let normalized = path.replace('\\', "/").to_lowercase();
    let components: Vec<&str> = normalized.split('/').collect();

    if components.iter().any(|component| {
        matches!(
            *component,
            "test" | "tests" | "__tests__" | "spec" | "specs"
        )
    }) {
        return true;
    }

    let file_name = components.last().copied().unwrap_or_default();
    let stem = file_name
        .rsplit_once('.')
        .map(|(stem, _)| stem)
        .unwrap_or(file_name);

    stem.ends_with("_test")
        || stem.ends_with(".test")
        || stem.ends_with(".spec")
        || stem.starts_with("test_")
        || stem == "test"
        || stem == "tests"
        || stem == "spec"
        || stem == "specs"
}

/// Return whether a named symbol follows a conventional test/benchmark name.
///
/// The path check is intentionally separate: a test helper in a test file is
/// still an observation source, while a production symbol named `Test...`
/// should not become a target of its own evidence edge.
pub fn is_test_symbol_name(name: &str) -> bool {
    fn has_conventional_prefix(name: &str, prefixes: &[&str]) -> bool {
        prefixes.iter().any(|prefix| {
            let Some(rest) = name.strip_prefix(prefix) else {
                return false;
            };
            rest.is_empty()
                || rest.starts_with('_')
                || rest.chars().next().is_some_and(|c| c.is_ascii_uppercase())
                || rest.chars().next().is_some_and(|c| c.is_ascii_digit())
        })
    }

    has_conventional_prefix(name, &["Test", "test"])
        || has_conventional_prefix(name, &["Benchmark", "benchmark", "bench"])
        || has_conventional_prefix(name, &["Fuzz", "fuzz"])
        || has_conventional_prefix(name, &["Example", "example"])
        || matches!(name.to_lowercase().as_str(), "it" | "describe")
}

/// A symbol is an executable-evidence observation when either its path or its
/// name identifies it as test code.
pub fn is_test_symbol(path: &str, name: &str) -> bool {
    is_test_path(path) || is_test_symbol_name(name)
}

/// Identify common assertion and test-framework failure calls so they can be
/// recorded as witnesses rather than mistaken for production targets.
pub fn is_assertion_call(call: &CallSite) -> bool {
    fn has_assertion_prefix(name: &str, prefix: &str) -> bool {
        let name = name.trim_end_matches('!');
        let Some(rest) = name.strip_prefix(prefix) else {
            return false;
        };
        rest.is_empty()
            || rest.starts_with('_')
            || rest.chars().next().is_some_and(|c| c.is_ascii_uppercase())
    }

    let callee = call.callee.to_lowercase();
    let receiver = call
        .receiver
        .as_deref()
        .unwrap_or_default()
        .trim()
        .to_lowercase();

    if has_assertion_prefix(&call.callee, "assert")
        || has_assertion_prefix(&call.callee, "require")
        || has_assertion_prefix(&call.callee, "expect")
        || has_assertion_prefix(&call.callee, "should")
    {
        return true;
    }

    if receiver == "t"
        || receiver == "tb"
        || receiver == "testing"
        || receiver == "assert"
        || receiver == "require"
        || receiver == "expect"
    {
        return matches!(
            callee.as_str(),
            "error"
                | "errorf"
                | "fatal"
                | "fatalf"
                | "fail"
                | "failnow"
                | "noerror"
                | "nil"
                | "notnil"
                | "equal"
                | "notequal"
                | "true"
                | "false"
                | "contains"
                | "notcontains"
                | "deep"
        );
    }

    false
}

/// Return whether an edge metadata object was generated by this experiment.
pub fn is_generated_edge(metadata: &serde_json::Value) -> bool {
    metadata.get("source").and_then(serde_json::Value::as_str) == Some(EDGE_SOURCE)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn call(callee: &str, receiver: Option<&str>) -> CallSite {
        CallSite {
            callee: callee.into(),
            receiver: receiver.map(str::to_string),
            node_text: format!("{callee}()"),
            line: 4,
        }
    }

    #[test]
    fn recognizes_common_test_paths() {
        assert!(is_test_path("src/service_test.go"));
        assert!(is_test_path("web/__tests__/stored.test.ts"));
        assert!(is_test_path("src/spec/transfer.rs"));
        assert!(!is_test_path("src/testdata/fixture.go"));
        assert!(!is_test_path("src/service.go"));
    }

    #[test]
    fn recognizes_test_names_without_overmatching_helpers() {
        assert!(is_test_symbol_name("TestStoredLifecycle"));
        assert!(is_test_symbol_name("test_manifest"));
        assert!(is_test_symbol_name("BenchmarkTransfer"));
        assert!(!is_test_symbol_name("newTestService"));
        assert!(!is_test_symbol_name("contest"));
    }

    #[test]
    fn recognizes_assertions_and_framework_failures() {
        assert!(is_assertion_call(&call("assert_eq", None)));
        assert!(is_assertion_call(&call("NoError", Some("require"))));
        assert!(is_assertion_call(&call("Fatalf", Some("t"))));
        assert!(!is_assertion_call(&call("assertion_helper", None)));
        assert!(!is_assertion_call(&call("SealManifest", None)));
        assert!(!is_assertion_call(&call("Error", Some("server"))));
    }

    #[test]
    fn recognizes_generated_metadata() {
        assert!(is_generated_edge(&serde_json::json!({
            "source": EDGE_SOURCE
        })));
        assert!(!is_generated_edge(&serde_json::json!({
            "source": "manual"
        })));
    }
}
